### ISSUE TITLE
Error using new profiles

### ISSUE THREAD

**Issue by manu-lifebit** [lifebit-ai/nf-rnaseq-salmon#2]
After creating and using a profile config (minimal_salmon_quant_test) I got this error:

![image](https://user-images.githubusercontent.com/85173414/148987012-f88059dd-d26b-4575-9516-8012928e2252.png)

So the main profile configuration has to be checked.

**Comment by ilevantis** [comment]
This is fixed in the PR #5 .

**Comment by manu-lifebit** [comment]
Perfect thanks

**Comment by manu-lifebit** [comment]
Error solved in https://github.com/lifebit-ai/nf-rnaseq-salmon/pull/5
Issue closed
